### ISSUE TITLE
What should I do with the Enumerable Entities?

### ISSUE THREAD

**Issue by andresh0816** [pipoburgos/SharedKernel#7]
Hey I'm using your library for make scalable apps, and in my applications I use lists for that ValueObjects that not need to change and are a list of them.

For example a School have many possible journeys and I need to have in the DB that, something like a enum but as an entity:

[
 { id: 1, name: "Morning Journey"},
 { id: 2, name: "Afternoon Journey"},
 { id: 3, name: "Night Journey"}
]

**Comment by pipoburgos** [comment]
Hi Andrés, thank you for your message. I'm a bit confused because first you mentioned objects of value without identifiers, but the example you provided has identifiers. Typically, a value object is characterized by not having an identifier. However, regardless of how the domain is modeled, it does not affect the mapping to a database. That's one of the advantages of Domain-Driven Design (DDD).

What database engine or ORM are you using?

**Comment by andresh0816** [comment]
Hi @pipoburgos thanks for answer my question.

Regarding to your question, I'm using SQL Server.

Yes, you're right with the data has indentifiers, and I would like to know which EntityType or class should I use for that kind of data. It's just a collection but with data.

**Comment by pipoburgos** [comment]
Hi Andres,

If an object has an identifier, it can be either an entity or a aggregate root (e.g. school, user, etc.). Otherwise, it is a value object (e.g. dates, car registration numbers, credit cards, etc.). If a root aggregate or entity has the same identifier as another, they are considered the same. On the other hand, a value object is immutable and only considered equal if all its properties are identical.
In the following link, you have an example. 'Escuela' is equivalent to 'bank account' and 'journey' is equivalent to 'movement'.
https://github.com/pipoburgos/SharedKernel/tree/master/samples/BankAccounts/src/Domain/BankAccounts.Domain/BankAccounts

 If you speak Spanish and have further questions, we can talk through mail or Telegram.  &#128521;

**Comment by andresh0816** [comment]
Hey @pipoburgos we can talk on Telegram. I have some questions about Domain Modulation. 

My telegram's user is andreshernandez1608.

Regards
